// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VTET.Data.Models;

public partial class OrderDetail
{
    public int Id { get; set; }

    public int? WatchId { get; set; }

    public int? OrderId { get; set; }

    public decimal? Price { get; set; }

    public int? Amount { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Tax { get; set; }

    public decimal? ShippingCost { get; set; }

    public DateTime? ShipmentDate { get; set; }

    public DateTime? EstimatedDeliveryDate { get; set; }

    public virtual Order Order { get; set; }

    public virtual Watch Watch { get; set; }
}