// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VTET.Data.Models;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int? WatchId { get; set; }

    public int? OrderId { get; set; }

    public int? Price { get; set; }

    public int? Amount { get; set; }

    public virtual Order Order { get; set; }

    public virtual Watch Watch { get; set; }
}